name: iOS CI

on:
  push: { branches: ["**"] }
  pull_request: { branches: ["**"] }

env:
  SCHEME: PokemonAnalyticsApp
  DEST: platform=iOS Simulator,name=iPhone 15

jobs:
  build-test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_15.4.app || \
          sudo xcode-select -s /Applications/Xcode.app
          xcodebuild -version

      - name: Locate Xcode project/workspace (robusto)
        id: locate
        run: |
          set -euo pipefail
          PROJ="$(git ls-files '**/*.xcodeproj' | head -n1 || true)"
          WORK="$(git ls-files '**/*.xcworkspace' | head -n1 || true)"
          if [ -z "$PROJ" ] && [ -z "$WORK" ]; then
            echo "::error::No .xcodeproj/.xcworkspace tracked in this branch."
            echo "Tree (3 niveles):"; find . -maxdepth 3 -print
            exit 1
          fi
          echo "PROJ=$PROJ" >> $GITHUB_ENV
          echo "WORK=$WORK" >> $GITHUB_ENV
          echo "Found project: ${PROJ:-<none>}"
          echo "Found workspace: ${WORK:-<none>}"

      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ~/Library/Caches/org.swift.swiftpm
            .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}

      - name: Resolve packages
        run: |
          if [ -n "$WORK" ]; then
            xcodebuild -workspace "$WORK" -resolvePackageDependencies
          else
            xcodebuild -project "$PROJ" -resolvePackageDependencies
          fi

      - name: Build & Test (SwiftLint plugin se ejecuta aquí)
        run: |
          set -o pipefail
          if [ -n "$WORK" ]; then
            xcodebuild -workspace "$WORK" -scheme "$SCHEME" -destination "$DEST" \
              -skipPackagePluginValidation -skipMacroValidation \
              clean test | tee xcodebuild.log
          else
            xcodebuild -project "$PROJ" -scheme "$SCHEME" -destination "$DEST" \
              -skipPackagePluginValidation -skipMacroValidation \
              clean test | tee xcodebuild.log
          fi
