name: iOS CI

on:
  push: { branches: ['**'] }
  pull_request: { branches: ['**'] }

jobs:
  build-test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      # Selecciona Xcode 16.2 (compatible con tu .xcodeproj)
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - run: xcodebuild -version

      # Resuelve dependencias SPM si las hay (fallará si el proyecto no referencia paquetes)
      - name: Resolve packages
        run: >
          xcodebuild
          -project "PokemonAnalyticsApp/PokemonAnalyticsApp.xcodeproj"
          -resolvePackageDependencies

      # Build + Tests (el plugin de SwiftLint corre durante el build si está agregado)
      - name: Build & Test
        run: >
          set -o pipefail &&
          xcodebuild
          -project "PokemonAnalyticsApp/PokemonAnalyticsApp.xcodeproj"
          -scheme "PokemonAnalyticsApp"
          -destination "platform=iOS Simulator,OS=latest,name=iPhone 16"
          -skipPackagePluginValidation -skipMacroValidation
          clean test | tee xcodebuild.log

