name: iOS CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build-test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_15.4.app || sudo xcode-select -s /Applications/Xcode.app
          xcodebuild -version

      - name: Resolve packages
        run: xcodebuild -project PokemonAnalyticsApp/PokemonAnalyticsApp.xcodeproj -resolvePackageDependencies

      - name: Build & Test (runs SwiftLint plugin if attached)
        run: |
          set -o pipefail
          xcodebuild \
            -project PokemonAnalyticsApp/PokemonAnalyticsApp.xcodeproj \
            -scheme "PokemonAnalyticsApp" \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -skipPackagePluginValidation -skipMacroValidation \
            clean test | tee xcodebuild.log
