name: iOS CI
on:
  push: { branches: ["**"] }
  pull_request: { branches: ["**"] }

jobs:
  build-test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_15.4.app || \
          sudo xcode-select -s /Applications/Xcode.app
          xcodebuild -version

      - name: Debug tree
        run: |
          ls -la
          ls -la PokemonAnalyticsApp

      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ~/Library/Caches/org.swift.swiftpm
            .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}

      - name: Resolve packages
        working-directory: PokemonAnalyticsApp
        run: xcodebuild -project PokemonAnalyticsApp.xcodeproj -resolvePackageDependencies

      - name: Build & Test (runs SwiftLint plugin too)
        working-directory: PokemonAnalyticsApp
        run: |
          set -o pipefail
          xcodebuild \
            -project PokemonAnalyticsApp.xcodeproj \
            -scheme "PokemonAnalyticsApp" \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -skipPackagePluginValidation -skipMacroValidation \
            clean test | tee xcodebuild.log
