name: iOS CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_15.4.app || \
          sudo xcode-select -s /Applications/Xcode.app
          xcodebuild -version

      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ~/Library/Caches/org.swift.swiftpm
            .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}

      - name: Resolve packages
        run: xcodebuild -resolvePackageDependencies

      - name: Build & Test (runs SwiftLint plugin too)
        run: |
          set -o pipefail
          xcodebuild \
            -scheme "PokemonAnalyticsApp" \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -skipPackagePluginValidation -skipMacroValidation \
            clean test | tee xcodebuild.log
