name: iOS CI
on:
  push: { branches: ['**'] }
  pull_request: { branches: ['**'] }

jobs:
  build-test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Use Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - run: xcodebuild -version

      - name: Resolve packages (if any)
        run: |
          PROJ=PokemonAnalyticsApp/PokemonAnalyticsApp.xcodeproj
          if grep -q 'XCRemoteSwiftPackageReference' "$PROJ/project.pbxproj"; then
            xcodebuild -project "$PROJ" -resolvePackageDependencies
          else
            echo "No SPM packages referenced → skipping."
          fi

      - name: Build & Test
        run: |
          set -o pipefail
          xcodebuild \
            -project PokemonAnalyticsApp/PokemonAnalyticsApp.xcodeproj \
            -scheme "PokemonAnalyticsApp" \
            -destination 'platform=iOS Simulator,OS=latest,name=iPhone 15' \
            -skipPackagePluginValidation -skipMacroValidation \
            clean test | tee xcodebuild.log

